# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjPfBVZ9ZTqofv65voc4Cl94kRGlXdrE
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import models

# Load dataset
(x_train, _), (x_test, _) = tf.keras.datasets.fashion_mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

# Add noise
noise=0.3
x_train_noisy=np.clip(x_train+noise*np.random.randn(*x_train.shape),0.,1.)
x_test_noisy=np.clip(x_test+noise*np.random.randn(*x_test.shape),0.,1.)

# Autoencoder model
model=models.Sequential([
    tf.keras.layers.Conv2D(16,3,activation='relu',padding='same',input_shape=(28,28,1)),
    tf.keras.layers.Conv2DTranspose(1,3,activation='sigmoid',padding='same')
])

# Compile and train
model.compile(optimizer='adam',loss='binary_crossentropy')

model.fit(x_train_noisy.reshape(-1,28,28,1),
          x_train.reshape(-1,28,28,1),
          epochs=3)

# Predict denoised image
output=model.predict(x_test_noisy[:1].reshape(-1,28,28,1))

# Display image
plt.imshow(output[0].reshape(28,28), cmap='gray')
plt.title("Denoised Image")
plt.show()