# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7Gbh20XMyg5sAAOgbdYvjmcrytJEEVh
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers,models

# Sequence data
X = np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]])
y = np.array([4,5,6,7])

# Reshape data
X = X.reshape((4,3,1))

# LSTM model
model = models.Sequential([
    layers.LSTM(10, input_shape=(3,1)),
    layers.Dense(1)
])

# Compile and train
model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=50)

# Prediction
print(model.predict(X))