# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwiIuRaJEGKWqRNDXXO7SLBuDL-7Bs8C
"""

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import datasets,layers,models

# Load dataset
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.fashion_mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

# Convert grayscale to RGB
x_train=tf.image.grayscale_to_rgb(tf.expand_dims(x_train,-1))
x_test=tf.image.grayscale_to_rgb(tf.expand_dims(x_test,-1))

# Load pretrained MobileNet
base=MobileNetV2(weights='imagenet',include_top=False,input_shape=(32,32,3))
base.trainable=False

# Transfer learning model
model=models.Sequential([
    base,
    layers.Flatten(),
    layers.Dense(10,activation='softmax')
])

# Compile and train
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Resize images to 32x32 to match MobileNetV2 input requirements
x_train_resized = tf.image.resize(x_train, (32, 32))
x_test_resized = tf.image.resize(x_test, (32, 32))

model.fit(x_train_resized, y_train, epochs=3)

# Evaluate
print("Accuracy:",model.evaluate(x_test_resized,y_test)[1])