# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwiIuRaJEGKWqRNDXXO7SLBuDL-7Bs8C
"""

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import datasets,layers,models

# Load dataset
(x_train,y_train),(x_test,y_test)=datasets.cifar10.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

# Load pretrained model
base=ResNet50(weights='imagenet',include_top=False,input_shape=(32,32,3))
base.trainable=False

# Fine-tuning model
model=models.Sequential([
    base,
    layers.Flatten(),
    layers.Dense(10,activation='softmax')
])

# Compile and train
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train,y_train,epochs=3)

# Evaluate
print("Accuracy:",model.evaluate(x_test,y_test)[1])
print("Loss:",model.evaluate(x_test,y_test)[0])

