# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7Gbh20XMyg5sAAOgbdYvjmcrytJEEVh
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

def generate_sequence(n_timesteps):
    x = np.linspace(0, 50, n_timesteps)
    y = np.sin(x)
    return y

n_timesteps = 100
sequence = generate_sequence(n_timesteps)

X, y = [], []
seq_length = 10

for i in range(len(sequence) - seq_length):
    X.append(sequence[i:i+seq_length])
    y.append(sequence[i+seq_length])

X, y = np.array(X), np.array(y)
X = X.reshape((X.shape[0], X.shape[1], 1))

model = Sequential([
    SimpleRNN(10, activation='relu', return_sequences=False,input_shape=(seq_length, 1)),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=100, verbose=1)
predictions = model.predict(X)

print("Expected Output:", y[:5])
print("Predicted Output:", predictions[:5].flatten())