# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s7Gbh20XMyg5sAAOgbdYvjmcrytJEEVh
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers,models,datasets

# Load MNIST dataset
(x_train,_),(_,_) = datasets.mnist.load_data()
x_train = x_train/255.0
x_train = x_train.reshape(-1,28,28,1)

# Generator model
generator = models.Sequential([
    layers.Dense(784, activation='sigmoid', input_shape=(100,)),
    layers.Reshape((28,28,1))
])

# Discriminator model
discriminator = models.Sequential([
    layers.Flatten(input_shape=(28,28,1)),
    layers.Dense(1, activation='sigmoid')
])

# Compile discriminator
discriminator.compile(optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

# Generate image from random noise
noise = np.random.randn(1,100)
generated_image = generator.predict(noise)

# Display generated image
plt.imshow(generated_image[0,:,:,0], cmap='gray')
plt.title("Generated MNIST Image")
plt.show()